---
- name: Install Jenkins on host1
  hosts: host1
  gather_facts: true
  become: yes
  become_user: root
  vars:
  download_url1: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
  download_folder1: /opt
  java_name1: "{{download_folder1}}/jdk1.8.0_05"
  java_archive1: "{{download_folder1}}/jdk-8u5-linux-x64.tar.gz"

  tasks:
    - name: Download Java
      command: "wget -q -O {{java_archive1}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url1}} creates={{java_archive1}}"
    - name: Unpack archive
      command: "tar -zxf {{java_archive1}} -C {{download_folder1}} creates={{java_name1}}"
    - name: Fix ownership
      file: state=directory path={{java_name1}} owner=root group=root recurse=yes
    - name: Make Java available for system
      command: 'alternatives --install "/usr/bin/java" "java" "{{java_name1}}/bin/java" 2000'
    - name: Clean up
      file: state=absent path={{java_archive1}}

