---

#- name: Install Java on host1
 # yum:
  #  name: "{{java.VERSION}}"
   # state: latest
 # become: true

#- name: Change the default java version
 # alternatives:
  #   name: java
   #  link: /bin/java
    # path: "{{java.ALTERNATIVES}}"

- name: Download Jenkins
  get_url:
    url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest=/etc/yum.repos.d/jenkins.repo
  become: true

- name: Import GPG key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins
  yum:
    name: jenkins
    state: present

#- name: modify jenkins java options
 # lineinfile:
  #  dest=/etc/sysconfig/jenkins
   # regexp=^JENKINS_JAVA_OPTIONS=
    #line="JENKINS_JAVA_OPTIONS='-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false'"
 # become: true

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes


